name: Build, Push Docker Image, and Update Monorepo

on:
  push:
    tags:
      - stg-v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Download Dependencies
        run: go mod tidy

      - name: Run Tests
        run: go test -v ./...

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Tag Name
        id: extract_tag
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "::set-output name=image_tag::$IMAGE_TAG"

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/service-go:${{ env.IMAGE_TAG }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/service-go:${{ env.IMAGE_TAG }}

    outputs:
      image_tag: ${{ steps.extract_tag.outputs.image_tag }}

  update-monorepo:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MONOREPO_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone monorepo-gitops repository
        run: |
          git clone git@github.com:shaldyrz/monorepo-gitops.git
          cd monorepo-gitops
          ls -lah

      - name: Modify deployment.yaml with sed
        run: |
          cd monorepo-gitops
          sed -i 's|image: shaldyrz/service-go:.*|image: shaldyrz/service-go:${{ needs.build-and-push.outputs.image_tag }}|' staging/infrastructure-team/service-go/deployment.yaml

      - name: Commit and Push Changes
        run: |
          cd monorepo-gitops
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add staging/infrastructure-team/service-go/deployment.yaml
          git commit -m "Auto-update deployment.yaml to image tag ${{ needs.build-and-push.outputs.image_tag }}"
          git push origin main
