name: Update Monorepo GitOps Staging

on:
  workflow_run:
    workflows: ["Build and Push Docker Image Staging"]
    types:
      - completed

jobs:
  update-monorepo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch Image Tag
        id: get-tag
        run: |
          RUN_ID=${{ github.event.workflow_run.id }}
          IMAGE_TAG=$(gh run view $RUN_ID --json jobs --jq '.jobs[].outputs.image_tag')
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MONOREPO_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone monorepo-gitops repository
        run: |
          git clone git@github.com:shaldyrz/monorepo-gitops.git
          cd monorepo-gitops
          ls -lah

      - name: Modify deployment.yaml with sed
        run: |
          pwd
          ls -lah
          sed -i 's|image: shaldyrz/service-go:.*|image: shaldyrz/service-go:'"${IMAGE_TAG}"'|' monorepo-gitops/staging/infrastructure-team/service-go/deployment.yaml

      - name: Commit and Push Changes
        run: |
          cd monorepo-gitops
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add staging/infrastructure-team/service-go/deployment.yaml
          git commit -m "Auto-update deployment.yaml to image tag $IMAGE_TAG"
          git push origin main
