name: Update Monorepo GitOps Staging

on:
  workflow_run:
    workflows: ["Build and Push Docker Image Staging"]
    types:
      - completed

jobs:
  update-monorepo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MONOREPO_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone monorepo-gitops repository
        run: |
          git clone git@github.com:shaldyrz/monorepo-gitops.git
          cd monorepo-gitops

      - name: Extract Image Tag
        run: |
          IMAGE_TAG=${{ github.event.workflow_run.head_sha }}
          IMAGE_SHORT=$(echo $IMAGE_TAG | cut -c1-7)
          echo "IMAGE_SHORT=$IMAGE_SHORT" >> $GITHUB_ENV

      - name: Modify deployment.yaml with sed
        run: |
          sed -i 's|image: shaldyrz/service-go:.*|image: shaldyrz/service-go:'"${IMAGE_SHORT}"'|' monorepo-gitops/staging/infrastructure-team/service-go/deployment.yaml

      - name: Commit and Push Changes
        run: |
          cd monorepo-gitops
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add staging/infrastructure-team/service-go/deployment.yaml
          git commit -m "Auto-update deployment.yaml to image tag $IMAGE_SHORT"
          git push origin main